//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBV.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=manhcuong-pc\\sqlexpress;Initial Catalog= QLBV_PMEM;User ID=sa;Passwor" +
            "d= 123456")]
        public string QLBVConnectionString {
            get {
                return ((string)(this["QLBVConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://congdulieuyte.vn/hPortal/services/WSPortal")]
        public string QLBV_vn_congdulieuyte_WSPortalService {
            get {
                return ((string)(this["QLBV_vn_congdulieuyte_WSPortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytchilinhadmin.vnpt-invoice.com.vn/BusinessService.asmx")]
        public string QLBV_InvBusinessService30003_BusinessService {
            get {
                return ((string)(this["QLBV_InvBusinessService30003_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytkinhmonadmin.vnpt-invoice.com.vn/BusinessService.asmx")]
        public string QLBV_InvBusinessService_BusinessService {
            get {
                return ((string)(this["QLBV_InvBusinessService_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bvdktukycadmin.vnpt-invoice.com.vn/BusinessService.asmx")]
        public string QLBV_InvBusinessService30007_BusinessService {
            get {
                return ((string)(this["QLBV_InvBusinessService30007_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytcamgiangadmin.vnpt-invoice.com.vn/Businessservice.asmx")]
        public string QLBV_InvBusinessservice30012_BusinessService {
            get {
                return ((string)(this["QLBV_InvBusinessservice30012_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytkinhmonadmindemo.vnpt-invoice.com.vn/BusinessService.asmx")]
        public string QLBV_InvBusinessServicedemo_BusinessService {
            get {
                return ((string)(this["QLBV_InvBusinessServicedemo_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytchilinhadmindemo.vnpt-invoice.com.vn/Businessservice.asmx")]
        public string QLBV_InvBusinessservicedemo30003_BusinessService {
            get {
                return ((string)(this["QLBV_InvBusinessservicedemo30003_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bvdktukyadmindemo.vnpt-invoice.com.vn/BusinessService.asmx")]
        public string QLBV_InvBusinessServiceDemo30007_BusinessService {
            get {
                return ((string)(this["QLBV_InvBusinessServiceDemo30007_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytkinhmonadmin.vnpt-invoice.com.vn/PortalService.asmx")]
        public string QLBV_InvPortalService_PortalService {
            get {
                return ((string)(this["QLBV_InvPortalService_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytchilinhadmin.vnpt-invoice.com.vn/PortalService.asmx")]
        public string QLBV_InvPortalService30003_PortalService {
            get {
                return ((string)(this["QLBV_InvPortalService30003_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bvdktukycadmin.vnpt-invoice.com.vn/PortalService.asmx")]
        public string QLBV_InvPortalService30007_PortalService {
            get {
                return ((string)(this["QLBV_InvPortalService30007_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytcamgiangadmin.vnpt-invoice.com.vn/portalservice.asmx")]
        public string QLBV_InvPortalservice30012_PortalService {
            get {
                return ((string)(this["QLBV_InvPortalservice30012_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytkinhmonadmindemo.vnpt-invoice.com.vn/PortalService.asmx")]
        public string QLBV_InvPortalServicedemo_PortalService {
            get {
                return ((string)(this["QLBV_InvPortalServicedemo_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytchilinhadmindemo.vnpt-invoice.com.vn/Portalservice.asmx")]
        public string QLBV_InvPortalservicedemo30003_PortalService {
            get {
                return ((string)(this["QLBV_InvPortalservicedemo30003_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bvdktukyadmindemo.vnpt-invoice.com.vn/PortalService.asmx")]
        public string QLBV_InvPortalServiceDemo30007_PortalService {
            get {
                return ((string)(this["QLBV_InvPortalServiceDemo30007_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytkinhmonadmin.vnpt-invoice.com.vn/PublishService.asmx")]
        public string QLBV_InvPublishService_PublishService {
            get {
                return ((string)(this["QLBV_InvPublishService_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytchilinhadmin.vnpt-invoice.com.vn/Publishservice.asmx")]
        public string QLBV_InvPublishservice30003_PublishService {
            get {
                return ((string)(this["QLBV_InvPublishservice30003_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bvdktukycadmin.vnpt-invoice.com.vn/PublishService.asmx")]
        public string QLBV_InvPublishService30007_PublishService {
            get {
                return ((string)(this["QLBV_InvPublishService30007_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytcamgiangadmin.vnpt-invoice.com.vn/publishservice.asmx")]
        public string QLBV_InvPublishservice30012_PublishService {
            get {
                return ((string)(this["QLBV_InvPublishservice30012_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytkinhmonadmindemo.vnpt-invoice.com.vn/PublishService.asmx")]
        public string QLBV_InvPublishServicedemo_PublishService {
            get {
                return ((string)(this["QLBV_InvPublishServicedemo_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytchilinhadmindemo.vnpt-invoice.com.vn/publishservice.asmx")]
        public string QLBV_InvPublishservicedemo30003_PublishService {
            get {
                return ((string)(this["QLBV_InvPublishservicedemo30003_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bvdktukyadmindemo.vnpt-invoice.com.vn/PublishService.asmx")]
        public string QLBV_InvPublishServiceDemo30007_PublishService {
            get {
                return ((string)(this["QLBV_InvPublishServiceDemo30007_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bvmatbnh-tt78admindemo.vnpt-invoice.com.vn/PublishService.asmx")]
        public string QLBV_InvPublishServiceDemo27022_PublishService {
            get {
                return ((string)(this["QLBV_InvPublishServiceDemo27022_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bvmatbnh-tt78admindemo.vnpt-invoice.com.vn/PublishService.asmx")]
        public string QLBV_InvPublishService27022_PublishService {
            get {
                return ((string)(this["QLBV_InvPublishService27022_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bvmatbnh-tt78admindemo.vnpt-invoice.com.vn/PortalService.asmx")]
        public string QLBV_InvPortalService27022_PortalService {
            get {
                return ((string)(this["QLBV_InvPortalService27022_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytchilinh-tt78admindemo.vnpt-invoice.com.vn/PublishService.asmx")]
        public string QLBV_InvPublishservicedemo30003_TT78_PublishService {
            get {
                return ((string)(this["QLBV_InvPublishservicedemo30003_TT78_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytchilinh-tt78admindemo.vnpt-invoice.com.vn/PortalService.asmx")]
        public string QLBV_InvPortalServicedemo30003_TT78_PortalService {
            get {
                return ((string)(this["QLBV_InvPortalServicedemo30003_TT78_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytchilinh-tt78admindemo.vnpt-invoice.com.vn/BusinessService.asmx")]
        public string QLBV_InvBusinessservicedemo30003_TT78_BusinessService {
            get {
                return ((string)(this["QLBV_InvBusinessservicedemo30003_TT78_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytchilinh-tt78admindemo.vnpt-invoice.com.vn/PortalService.asmx")]
        public string QLBV_InvPotalServicedemo_30003_TT78_PortalService {
            get {
                return ((string)(this["QLBV_InvPotalServicedemo_30003_TT78_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytchilinh-tt78admin.vnpt-invoice.com.vn/PublishService.asmx")]
        public string QLBV_InvPublishserviceCongThat30003_TT78_PublishService {
            get {
                return ((string)(this["QLBV_InvPublishserviceCongThat30003_TT78_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytchilinh-tt78admin.vnpt-invoice.com.vn/PortalService.asmx")]
        public string QLBV_InvPortalServiceCongThat30003_TT78_PortalService {
            get {
                return ((string)(this["QLBV_InvPortalServiceCongThat30003_TT78_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytchilinh-tt78admin.vnpt-invoice.com.vn/BusinessService.asmx")]
        public string QLBV_InvBusinessserviceCongThat30003_TT78_BusinessService {
            get {
                return ((string)(this["QLBV_InvBusinessserviceCongThat30003_TT78_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytcamgiang-tt78admindemo.vnpt-invoice.com.vn/PortalService.asmx")]
        public string QLBV_InvPortalServicedemo_30012_TT78_PortalService {
            get {
                return ((string)(this["QLBV_InvPortalServicedemo_30012_TT78_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytcamgiang-tt78admindemo.vnpt-invoice.com.vn/PublishService.asmx")]
        public string QLBV_InvPublishServicedemo_30012_TT78_PublishService {
            get {
                return ((string)(this["QLBV_InvPublishServicedemo_30012_TT78_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://2300244498-tt78cadmin.vnpt-invoice.com.vn/PortalService.asmx")]
        public string QLBV_InvPortalServiceCongThat_27022_TT78_PortalService {
            get {
                return ((string)(this["QLBV_InvPortalServiceCongThat_27022_TT78_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://2300244498-tt78cadmin.vnpt-invoice.com.vn/PublishService.asmx")]
        public string QLBV_InvPublishServiceCongThat_27022_TT78_PublishService {
            get {
                return ((string)(this["QLBV_InvPublishServiceCongThat_27022_TT78_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytcamgiang-tt78admin.vnpt-invoice.com.vn/PortalService.asmx")]
        public string QLBV_InvPortalServiceCongThat_30012_TT78_PortalService {
            get {
                return ((string)(this["QLBV_InvPortalServiceCongThat_30012_TT78_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttytcamgiang-tt78admin.vnpt-invoice.com.vn/PublishService.asmx")]
        public string QLBV_InvPublishServiceCongThat_30012_TT78_PublishService {
            get {
                return ((string)(this["QLBV_InvPublishServiceCongThat_30012_TT78_PublishService"]));
            }
        }
    }
}
