//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBV.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://congdulieuyte.vn/hPortal/services/WSPortal", ConfigurationName="ServiceReference1.WSPortal")]
    public interface WSPortal {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws) of message guiTTNVRequest does not match the default value (https://congdulieuyte.vn/hPortal/services/WSPortal)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        QLBV.ServiceReference1.guiTTNVResponse guiTTNV(QLBV.ServiceReference1.guiTTNVRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws) of message guiTTXVRequest does not match the default value (https://congdulieuyte.vn/hPortal/services/WSPortal)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        QLBV.ServiceReference1.guiTTXVResponse guiTTXV(QLBV.ServiceReference1.guiTTXVRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws) of message guiTTCTRequest does not match the default value (https://congdulieuyte.vn/hPortal/services/WSPortal)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        QLBV.ServiceReference1.guiTTCTResponse guiTTCT(QLBV.ServiceReference1.guiTTCTRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws) of message kt_tt_theBHYTRequest does not match the default value (https://congdulieuyte.vn/hPortal/services/WSPortal)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        QLBV.ServiceReference1.kt_tt_theBHYTResponse kt_tt_theBHYT(QLBV.ServiceReference1.kt_tt_theBHYTRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws) of message tc_tt_theBHYTRequest does not match the default value (https://congdulieuyte.vn/hPortal/services/WSPortal)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        QLBV.ServiceReference1.tc_tt_theBHYTResponse tc_tt_theBHYT(QLBV.ServiceReference1.tc_tt_theBHYTRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws) of message nhanTTCTRequest does not match the default value (https://congdulieuyte.vn/hPortal/services/WSPortal)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        QLBV.ServiceReference1.nhanTTCTResponse nhanTTCT(QLBV.ServiceReference1.nhanTTCTRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws) of message tc_ls_KCBRequest does not match the default value (https://congdulieuyte.vn/hPortal/services/WSPortal)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        QLBV.ServiceReference1.tc_ls_KCBResponse tc_ls_KCB(QLBV.ServiceReference1.tc_ls_KCBRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws) of message guiDTTRequest does not match the default value (https://congdulieuyte.vn/hPortal/services/WSPortal)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        QLBV.ServiceReference1.guiDTTResponse guiDTT(QLBV.ServiceReference1.guiDTTRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws) of message nhanDTTRequest does not match the default value (https://congdulieuyte.vn/hPortal/services/WSPortal)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        QLBV.ServiceReference1.nhanDTTResponse nhanDTT(QLBV.ServiceReference1.nhanDTTRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws) of message guiDDTTRequest does not match the default value (https://congdulieuyte.vn/hPortal/services/WSPortal)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        QLBV.ServiceReference1.guiDDTTResponse guiDDTT(QLBV.ServiceReference1.guiDDTTRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws) of message nhanDDTTRequest does not match the default value (https://congdulieuyte.vn/hPortal/services/WSPortal)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        QLBV.ServiceReference1.nhanDDTTResponse nhanDDTT(QLBV.ServiceReference1.nhanDDTTRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws) of message kt_lamdungtheRequest does not match the default value (https://congdulieuyte.vn/hPortal/services/WSPortal)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        QLBV.ServiceReference1.kt_lamdungtheResponse kt_lamdungthe(QLBV.ServiceReference1.kt_lamdungtheRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws) of message ws_dyncallRequest does not match the default value (https://congdulieuyte.vn/hPortal/services/WSPortal)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        QLBV.ServiceReference1.ws_dyncallResponse ws_dyncall(QLBV.ServiceReference1.ws_dyncallRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guiTTNV", WrapperNamespace="http://ws", IsWrapped=true)]
    public partial class guiTTNVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string _usr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string _pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string xmlData;
        
        public guiTTNVRequest() {
        }
        
        public guiTTNVRequest(string _usr, string _pwd, string xmlData) {
            this._usr = _usr;
            this._pwd = _pwd;
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guiTTNVResponse", WrapperNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal", IsWrapped=true)]
    public partial class guiTTNVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string guiTTNVReturn;
        
        public guiTTNVResponse() {
        }
        
        public guiTTNVResponse(string guiTTNVReturn) {
            this.guiTTNVReturn = guiTTNVReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guiTTXV", WrapperNamespace="http://ws", IsWrapped=true)]
    public partial class guiTTXVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string _usr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string _pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string xmlData;
        
        public guiTTXVRequest() {
        }
        
        public guiTTXVRequest(string _usr, string _pwd, string xmlData) {
            this._usr = _usr;
            this._pwd = _pwd;
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guiTTXVResponse", WrapperNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal", IsWrapped=true)]
    public partial class guiTTXVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string guiTTXVReturn;
        
        public guiTTXVResponse() {
        }
        
        public guiTTXVResponse(string guiTTXVReturn) {
            this.guiTTXVReturn = guiTTXVReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guiTTCT", WrapperNamespace="http://ws", IsWrapped=true)]
    public partial class guiTTCTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string _usr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string _pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string xmlData;
        
        public guiTTCTRequest() {
        }
        
        public guiTTCTRequest(string _usr, string _pwd, string xmlData) {
            this._usr = _usr;
            this._pwd = _pwd;
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guiTTCTResponse", WrapperNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal", IsWrapped=true)]
    public partial class guiTTCTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string guiTTCTReturn;
        
        public guiTTCTResponse() {
        }
        
        public guiTTCTResponse(string guiTTCTReturn) {
            this.guiTTCTReturn = guiTTCTReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="kt_tt_theBHYT", WrapperNamespace="http://ws", IsWrapped=true)]
    public partial class kt_tt_theBHYTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string _usr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string _pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string xmlData;
        
        public kt_tt_theBHYTRequest() {
        }
        
        public kt_tt_theBHYTRequest(string _usr, string _pwd, string xmlData) {
            this._usr = _usr;
            this._pwd = _pwd;
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="kt_tt_theBHYTResponse", WrapperNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal", IsWrapped=true)]
    public partial class kt_tt_theBHYTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string kt_tt_theBHYTReturn;
        
        public kt_tt_theBHYTResponse() {
        }
        
        public kt_tt_theBHYTResponse(string kt_tt_theBHYTReturn) {
            this.kt_tt_theBHYTReturn = kt_tt_theBHYTReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tc_tt_theBHYT", WrapperNamespace="http://ws", IsWrapped=true)]
    public partial class tc_tt_theBHYTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string _usr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string _pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string xmlData;
        
        public tc_tt_theBHYTRequest() {
        }
        
        public tc_tt_theBHYTRequest(string _usr, string _pwd, string xmlData) {
            this._usr = _usr;
            this._pwd = _pwd;
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tc_tt_theBHYTResponse", WrapperNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal", IsWrapped=true)]
    public partial class tc_tt_theBHYTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string tc_tt_theBHYTReturn;
        
        public tc_tt_theBHYTResponse() {
        }
        
        public tc_tt_theBHYTResponse(string tc_tt_theBHYTReturn) {
            this.tc_tt_theBHYTReturn = tc_tt_theBHYTReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanTTCT", WrapperNamespace="http://ws", IsWrapped=true)]
    public partial class nhanTTCTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string _usr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string _pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string xmlData;
        
        public nhanTTCTRequest() {
        }
        
        public nhanTTCTRequest(string _usr, string _pwd, string xmlData) {
            this._usr = _usr;
            this._pwd = _pwd;
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanTTCTResponse", WrapperNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal", IsWrapped=true)]
    public partial class nhanTTCTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nhanTTCTReturn;
        
        public nhanTTCTResponse() {
        }
        
        public nhanTTCTResponse(string nhanTTCTReturn) {
            this.nhanTTCTReturn = nhanTTCTReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tc_ls_KCB", WrapperNamespace="http://ws", IsWrapped=true)]
    public partial class tc_ls_KCBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string _usr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string _pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string xmlData;
        
        public tc_ls_KCBRequest() {
        }
        
        public tc_ls_KCBRequest(string _usr, string _pwd, string xmlData) {
            this._usr = _usr;
            this._pwd = _pwd;
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tc_ls_KCBResponse", WrapperNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal", IsWrapped=true)]
    public partial class tc_ls_KCBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string tc_ls_KCBReturn;
        
        public tc_ls_KCBResponse() {
        }
        
        public tc_ls_KCBResponse(string tc_ls_KCBReturn) {
            this.tc_ls_KCBReturn = tc_ls_KCBReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guiDTT", WrapperNamespace="http://ws", IsWrapped=true)]
    public partial class guiDTTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string _usr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string _pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string xmlData;
        
        public guiDTTRequest() {
        }
        
        public guiDTTRequest(string _usr, string _pwd, string xmlData) {
            this._usr = _usr;
            this._pwd = _pwd;
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guiDTTResponse", WrapperNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal", IsWrapped=true)]
    public partial class guiDTTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string guiDTTReturn;
        
        public guiDTTResponse() {
        }
        
        public guiDTTResponse(string guiDTTReturn) {
            this.guiDTTReturn = guiDTTReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanDTT", WrapperNamespace="http://ws", IsWrapped=true)]
    public partial class nhanDTTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string _usr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string _pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string xmlData;
        
        public nhanDTTRequest() {
        }
        
        public nhanDTTRequest(string _usr, string _pwd, string xmlData) {
            this._usr = _usr;
            this._pwd = _pwd;
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanDTTResponse", WrapperNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal", IsWrapped=true)]
    public partial class nhanDTTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nhanDTTReturn;
        
        public nhanDTTResponse() {
        }
        
        public nhanDTTResponse(string nhanDTTReturn) {
            this.nhanDTTReturn = nhanDTTReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guiDDTT", WrapperNamespace="http://ws", IsWrapped=true)]
    public partial class guiDDTTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string _usr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string _pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string xmlData;
        
        public guiDDTTRequest() {
        }
        
        public guiDDTTRequest(string _usr, string _pwd, string xmlData) {
            this._usr = _usr;
            this._pwd = _pwd;
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guiDDTTResponse", WrapperNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal", IsWrapped=true)]
    public partial class guiDDTTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string guiDDTTReturn;
        
        public guiDDTTResponse() {
        }
        
        public guiDDTTResponse(string guiDDTTReturn) {
            this.guiDDTTReturn = guiDDTTReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanDDTT", WrapperNamespace="http://ws", IsWrapped=true)]
    public partial class nhanDDTTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string _usr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string _pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string xmlData;
        
        public nhanDDTTRequest() {
        }
        
        public nhanDDTTRequest(string _usr, string _pwd, string xmlData) {
            this._usr = _usr;
            this._pwd = _pwd;
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanDDTTResponse", WrapperNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal", IsWrapped=true)]
    public partial class nhanDDTTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nhanDDTTReturn;
        
        public nhanDDTTResponse() {
        }
        
        public nhanDDTTResponse(string nhanDDTTReturn) {
            this.nhanDDTTReturn = nhanDDTTReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="kt_lamdungthe", WrapperNamespace="http://ws", IsWrapped=true)]
    public partial class kt_lamdungtheRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string _usr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string _pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string xmlData;
        
        public kt_lamdungtheRequest() {
        }
        
        public kt_lamdungtheRequest(string _usr, string _pwd, string xmlData) {
            this._usr = _usr;
            this._pwd = _pwd;
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="kt_lamdungtheResponse", WrapperNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal", IsWrapped=true)]
    public partial class kt_lamdungtheResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string kt_lamdungtheReturn;
        
        public kt_lamdungtheResponse() {
        }
        
        public kt_lamdungtheResponse(string kt_lamdungtheReturn) {
            this.kt_lamdungtheReturn = kt_lamdungtheReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_dyncall", WrapperNamespace="http://ws", IsWrapped=true)]
    public partial class ws_dyncallRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string _usr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string _pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string svcId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string param;
        
        public ws_dyncallRequest() {
        }
        
        public ws_dyncallRequest(string _usr, string _pwd, string svcId, string param) {
            this._usr = _usr;
            this._pwd = _pwd;
            this.svcId = svcId;
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_dyncallResponse", WrapperNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal", IsWrapped=true)]
    public partial class ws_dyncallResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ws_dyncallReturn;
        
        public ws_dyncallResponse() {
        }
        
        public ws_dyncallResponse(string ws_dyncallReturn) {
            this.ws_dyncallReturn = ws_dyncallReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSPortalChannel : QLBV.ServiceReference1.WSPortal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSPortalClient : System.ServiceModel.ClientBase<QLBV.ServiceReference1.WSPortal>, QLBV.ServiceReference1.WSPortal {
        
        public WSPortalClient() {
        }
        
        public WSPortalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSPortalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPortalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPortalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QLBV.ServiceReference1.guiTTNVResponse QLBV.ServiceReference1.WSPortal.guiTTNV(QLBV.ServiceReference1.guiTTNVRequest request) {
            return base.Channel.guiTTNV(request);
        }
        
        public string guiTTNV(string _usr, string _pwd, string xmlData) {
            QLBV.ServiceReference1.guiTTNVRequest inValue = new QLBV.ServiceReference1.guiTTNVRequest();
            inValue._usr = _usr;
            inValue._pwd = _pwd;
            inValue.xmlData = xmlData;
            QLBV.ServiceReference1.guiTTNVResponse retVal = ((QLBV.ServiceReference1.WSPortal)(this)).guiTTNV(inValue);
            return retVal.guiTTNVReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QLBV.ServiceReference1.guiTTXVResponse QLBV.ServiceReference1.WSPortal.guiTTXV(QLBV.ServiceReference1.guiTTXVRequest request) {
            return base.Channel.guiTTXV(request);
        }
        
        public string guiTTXV(string _usr, string _pwd, string xmlData) {
            QLBV.ServiceReference1.guiTTXVRequest inValue = new QLBV.ServiceReference1.guiTTXVRequest();
            inValue._usr = _usr;
            inValue._pwd = _pwd;
            inValue.xmlData = xmlData;
            QLBV.ServiceReference1.guiTTXVResponse retVal = ((QLBV.ServiceReference1.WSPortal)(this)).guiTTXV(inValue);
            return retVal.guiTTXVReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QLBV.ServiceReference1.guiTTCTResponse QLBV.ServiceReference1.WSPortal.guiTTCT(QLBV.ServiceReference1.guiTTCTRequest request) {
            return base.Channel.guiTTCT(request);
        }
        
        public string guiTTCT(string _usr, string _pwd, string xmlData) {
            QLBV.ServiceReference1.guiTTCTRequest inValue = new QLBV.ServiceReference1.guiTTCTRequest();
            inValue._usr = _usr;
            inValue._pwd = _pwd;
            inValue.xmlData = xmlData;
            QLBV.ServiceReference1.guiTTCTResponse retVal = ((QLBV.ServiceReference1.WSPortal)(this)).guiTTCT(inValue);
            return retVal.guiTTCTReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QLBV.ServiceReference1.kt_tt_theBHYTResponse QLBV.ServiceReference1.WSPortal.kt_tt_theBHYT(QLBV.ServiceReference1.kt_tt_theBHYTRequest request) {
            return base.Channel.kt_tt_theBHYT(request);
        }
        
        public string kt_tt_theBHYT(string _usr, string _pwd, string xmlData) {
            QLBV.ServiceReference1.kt_tt_theBHYTRequest inValue = new QLBV.ServiceReference1.kt_tt_theBHYTRequest();
            inValue._usr = _usr;
            inValue._pwd = _pwd;
            inValue.xmlData = xmlData;
            QLBV.ServiceReference1.kt_tt_theBHYTResponse retVal = ((QLBV.ServiceReference1.WSPortal)(this)).kt_tt_theBHYT(inValue);
            return retVal.kt_tt_theBHYTReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QLBV.ServiceReference1.tc_tt_theBHYTResponse QLBV.ServiceReference1.WSPortal.tc_tt_theBHYT(QLBV.ServiceReference1.tc_tt_theBHYTRequest request) {
            return base.Channel.tc_tt_theBHYT(request);
        }
        
        public string tc_tt_theBHYT(string _usr, string _pwd, string xmlData) {
            QLBV.ServiceReference1.tc_tt_theBHYTRequest inValue = new QLBV.ServiceReference1.tc_tt_theBHYTRequest();
            inValue._usr = _usr;
            inValue._pwd = _pwd;
            inValue.xmlData = xmlData;
            QLBV.ServiceReference1.tc_tt_theBHYTResponse retVal = ((QLBV.ServiceReference1.WSPortal)(this)).tc_tt_theBHYT(inValue);
            return retVal.tc_tt_theBHYTReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QLBV.ServiceReference1.nhanTTCTResponse QLBV.ServiceReference1.WSPortal.nhanTTCT(QLBV.ServiceReference1.nhanTTCTRequest request) {
            return base.Channel.nhanTTCT(request);
        }
        
        public string nhanTTCT(string _usr, string _pwd, string xmlData) {
            QLBV.ServiceReference1.nhanTTCTRequest inValue = new QLBV.ServiceReference1.nhanTTCTRequest();
            inValue._usr = _usr;
            inValue._pwd = _pwd;
            inValue.xmlData = xmlData;
            QLBV.ServiceReference1.nhanTTCTResponse retVal = ((QLBV.ServiceReference1.WSPortal)(this)).nhanTTCT(inValue);
            return retVal.nhanTTCTReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QLBV.ServiceReference1.tc_ls_KCBResponse QLBV.ServiceReference1.WSPortal.tc_ls_KCB(QLBV.ServiceReference1.tc_ls_KCBRequest request) {
            return base.Channel.tc_ls_KCB(request);
        }
        
        public string tc_ls_KCB(string _usr, string _pwd, string xmlData) {
            QLBV.ServiceReference1.tc_ls_KCBRequest inValue = new QLBV.ServiceReference1.tc_ls_KCBRequest();
            inValue._usr = _usr;
            inValue._pwd = _pwd;
            inValue.xmlData = xmlData;
            QLBV.ServiceReference1.tc_ls_KCBResponse retVal = ((QLBV.ServiceReference1.WSPortal)(this)).tc_ls_KCB(inValue);
            return retVal.tc_ls_KCBReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QLBV.ServiceReference1.guiDTTResponse QLBV.ServiceReference1.WSPortal.guiDTT(QLBV.ServiceReference1.guiDTTRequest request) {
            return base.Channel.guiDTT(request);
        }
        
        public string guiDTT(string _usr, string _pwd, string xmlData) {
            QLBV.ServiceReference1.guiDTTRequest inValue = new QLBV.ServiceReference1.guiDTTRequest();
            inValue._usr = _usr;
            inValue._pwd = _pwd;
            inValue.xmlData = xmlData;
            QLBV.ServiceReference1.guiDTTResponse retVal = ((QLBV.ServiceReference1.WSPortal)(this)).guiDTT(inValue);
            return retVal.guiDTTReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QLBV.ServiceReference1.nhanDTTResponse QLBV.ServiceReference1.WSPortal.nhanDTT(QLBV.ServiceReference1.nhanDTTRequest request) {
            return base.Channel.nhanDTT(request);
        }
        
        public string nhanDTT(string _usr, string _pwd, string xmlData) {
            QLBV.ServiceReference1.nhanDTTRequest inValue = new QLBV.ServiceReference1.nhanDTTRequest();
            inValue._usr = _usr;
            inValue._pwd = _pwd;
            inValue.xmlData = xmlData;
            QLBV.ServiceReference1.nhanDTTResponse retVal = ((QLBV.ServiceReference1.WSPortal)(this)).nhanDTT(inValue);
            return retVal.nhanDTTReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QLBV.ServiceReference1.guiDDTTResponse QLBV.ServiceReference1.WSPortal.guiDDTT(QLBV.ServiceReference1.guiDDTTRequest request) {
            return base.Channel.guiDDTT(request);
        }
        
        public string guiDDTT(string _usr, string _pwd, string xmlData) {
            QLBV.ServiceReference1.guiDDTTRequest inValue = new QLBV.ServiceReference1.guiDDTTRequest();
            inValue._usr = _usr;
            inValue._pwd = _pwd;
            inValue.xmlData = xmlData;
            QLBV.ServiceReference1.guiDDTTResponse retVal = ((QLBV.ServiceReference1.WSPortal)(this)).guiDDTT(inValue);
            return retVal.guiDDTTReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QLBV.ServiceReference1.nhanDDTTResponse QLBV.ServiceReference1.WSPortal.nhanDDTT(QLBV.ServiceReference1.nhanDDTTRequest request) {
            return base.Channel.nhanDDTT(request);
        }
        
        public string nhanDDTT(string _usr, string _pwd, string xmlData) {
            QLBV.ServiceReference1.nhanDDTTRequest inValue = new QLBV.ServiceReference1.nhanDDTTRequest();
            inValue._usr = _usr;
            inValue._pwd = _pwd;
            inValue.xmlData = xmlData;
            QLBV.ServiceReference1.nhanDDTTResponse retVal = ((QLBV.ServiceReference1.WSPortal)(this)).nhanDDTT(inValue);
            return retVal.nhanDDTTReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QLBV.ServiceReference1.kt_lamdungtheResponse QLBV.ServiceReference1.WSPortal.kt_lamdungthe(QLBV.ServiceReference1.kt_lamdungtheRequest request) {
            return base.Channel.kt_lamdungthe(request);
        }
        
        public string kt_lamdungthe(string _usr, string _pwd, string xmlData) {
            QLBV.ServiceReference1.kt_lamdungtheRequest inValue = new QLBV.ServiceReference1.kt_lamdungtheRequest();
            inValue._usr = _usr;
            inValue._pwd = _pwd;
            inValue.xmlData = xmlData;
            QLBV.ServiceReference1.kt_lamdungtheResponse retVal = ((QLBV.ServiceReference1.WSPortal)(this)).kt_lamdungthe(inValue);
            return retVal.kt_lamdungtheReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QLBV.ServiceReference1.ws_dyncallResponse QLBV.ServiceReference1.WSPortal.ws_dyncall(QLBV.ServiceReference1.ws_dyncallRequest request) {
            return base.Channel.ws_dyncall(request);
        }
        
        public string ws_dyncall(string _usr, string _pwd, string svcId, string param) {
            QLBV.ServiceReference1.ws_dyncallRequest inValue = new QLBV.ServiceReference1.ws_dyncallRequest();
            inValue._usr = _usr;
            inValue._pwd = _pwd;
            inValue.svcId = svcId;
            inValue.param = param;
            QLBV.ServiceReference1.ws_dyncallResponse retVal = ((QLBV.ServiceReference1.WSPortal)(this)).ws_dyncall(inValue);
            return retVal.ws_dyncallReturn;
        }
    }
}
