//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace QLBV.vn.congdulieuyte {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSPortalSoapBinding", Namespace="https://congdulieuyte.vn/hPortal/services/WSPortal")]
    public partial class WSPortalService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback nhanDTTOperationCompleted;
        
        private System.Threading.SendOrPostCallback guiDDTTOperationCompleted;
        
        private System.Threading.SendOrPostCallback nhanDDTTOperationCompleted;
        
        private System.Threading.SendOrPostCallback kt_lamdungtheOperationCompleted;
        
        private System.Threading.SendOrPostCallback ws_dyncallOperationCompleted;
        
        private System.Threading.SendOrPostCallback guiTTNVOperationCompleted;
        
        private System.Threading.SendOrPostCallback guiTTXVOperationCompleted;
        
        private System.Threading.SendOrPostCallback guiTTCTOperationCompleted;
        
        private System.Threading.SendOrPostCallback kt_tt_theBHYTOperationCompleted;
        
        private System.Threading.SendOrPostCallback tc_tt_theBHYTOperationCompleted;
        
        private System.Threading.SendOrPostCallback nhanTTCTOperationCompleted;
        
        private System.Threading.SendOrPostCallback tc_ls_KCBOperationCompleted;
        
        private System.Threading.SendOrPostCallback guiDTTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSPortalService() {
            this.Url = global::QLBV.Properties.Settings.Default.QLBV_vn_congdulieuyte_WSPortalService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event nhanDTTCompletedEventHandler nhanDTTCompleted;
        
        /// <remarks/>
        public event guiDDTTCompletedEventHandler guiDDTTCompleted;
        
        /// <remarks/>
        public event nhanDDTTCompletedEventHandler nhanDDTTCompleted;
        
        /// <remarks/>
        public event kt_lamdungtheCompletedEventHandler kt_lamdungtheCompleted;
        
        /// <remarks/>
        public event ws_dyncallCompletedEventHandler ws_dyncallCompleted;
        
        /// <remarks/>
        public event guiTTNVCompletedEventHandler guiTTNVCompleted;
        
        /// <remarks/>
        public event guiTTXVCompletedEventHandler guiTTXVCompleted;
        
        /// <remarks/>
        public event guiTTCTCompletedEventHandler guiTTCTCompleted;
        
        /// <remarks/>
        public event kt_tt_theBHYTCompletedEventHandler kt_tt_theBHYTCompleted;
        
        /// <remarks/>
        public event tc_tt_theBHYTCompletedEventHandler tc_tt_theBHYTCompleted;
        
        /// <remarks/>
        public event nhanTTCTCompletedEventHandler nhanTTCTCompleted;
        
        /// <remarks/>
        public event tc_ls_KCBCompletedEventHandler tc_ls_KCBCompleted;
        
        /// <remarks/>
        public event guiDTTCompletedEventHandler guiDTTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws", ResponseNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal")]
        [return: System.Xml.Serialization.SoapElementAttribute("nhanDTTReturn")]
        public string nhanDTT(string _usr, string _pwd, string xmlData) {
            object[] results = this.Invoke("nhanDTT", new object[] {
                        _usr,
                        _pwd,
                        xmlData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nhanDTTAsync(string _usr, string _pwd, string xmlData) {
            this.nhanDTTAsync(_usr, _pwd, xmlData, null);
        }
        
        /// <remarks/>
        public void nhanDTTAsync(string _usr, string _pwd, string xmlData, object userState) {
            if ((this.nhanDTTOperationCompleted == null)) {
                this.nhanDTTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnhanDTTOperationCompleted);
            }
            this.InvokeAsync("nhanDTT", new object[] {
                        _usr,
                        _pwd,
                        xmlData}, this.nhanDTTOperationCompleted, userState);
        }
        
        private void OnnhanDTTOperationCompleted(object arg) {
            if ((this.nhanDTTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nhanDTTCompleted(this, new nhanDTTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws", ResponseNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal")]
        [return: System.Xml.Serialization.SoapElementAttribute("guiDDTTReturn")]
        public string guiDDTT(string _usr, string _pwd, string xmlData) {
            object[] results = this.Invoke("guiDDTT", new object[] {
                        _usr,
                        _pwd,
                        xmlData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void guiDDTTAsync(string _usr, string _pwd, string xmlData) {
            this.guiDDTTAsync(_usr, _pwd, xmlData, null);
        }
        
        /// <remarks/>
        public void guiDDTTAsync(string _usr, string _pwd, string xmlData, object userState) {
            if ((this.guiDDTTOperationCompleted == null)) {
                this.guiDDTTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguiDDTTOperationCompleted);
            }
            this.InvokeAsync("guiDDTT", new object[] {
                        _usr,
                        _pwd,
                        xmlData}, this.guiDDTTOperationCompleted, userState);
        }
        
        private void OnguiDDTTOperationCompleted(object arg) {
            if ((this.guiDDTTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guiDDTTCompleted(this, new guiDDTTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws", ResponseNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal")]
        [return: System.Xml.Serialization.SoapElementAttribute("nhanDDTTReturn")]
        public string nhanDDTT(string _usr, string _pwd, string xmlData) {
            object[] results = this.Invoke("nhanDDTT", new object[] {
                        _usr,
                        _pwd,
                        xmlData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nhanDDTTAsync(string _usr, string _pwd, string xmlData) {
            this.nhanDDTTAsync(_usr, _pwd, xmlData, null);
        }
        
        /// <remarks/>
        public void nhanDDTTAsync(string _usr, string _pwd, string xmlData, object userState) {
            if ((this.nhanDDTTOperationCompleted == null)) {
                this.nhanDDTTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnhanDDTTOperationCompleted);
            }
            this.InvokeAsync("nhanDDTT", new object[] {
                        _usr,
                        _pwd,
                        xmlData}, this.nhanDDTTOperationCompleted, userState);
        }
        
        private void OnnhanDDTTOperationCompleted(object arg) {
            if ((this.nhanDDTTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nhanDDTTCompleted(this, new nhanDDTTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws", ResponseNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal")]
        [return: System.Xml.Serialization.SoapElementAttribute("kt_lamdungtheReturn")]
        public string kt_lamdungthe(string _usr, string _pwd, string xmlData) {
            object[] results = this.Invoke("kt_lamdungthe", new object[] {
                        _usr,
                        _pwd,
                        xmlData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void kt_lamdungtheAsync(string _usr, string _pwd, string xmlData) {
            this.kt_lamdungtheAsync(_usr, _pwd, xmlData, null);
        }
        
        /// <remarks/>
        public void kt_lamdungtheAsync(string _usr, string _pwd, string xmlData, object userState) {
            if ((this.kt_lamdungtheOperationCompleted == null)) {
                this.kt_lamdungtheOperationCompleted = new System.Threading.SendOrPostCallback(this.Onkt_lamdungtheOperationCompleted);
            }
            this.InvokeAsync("kt_lamdungthe", new object[] {
                        _usr,
                        _pwd,
                        xmlData}, this.kt_lamdungtheOperationCompleted, userState);
        }
        
        private void Onkt_lamdungtheOperationCompleted(object arg) {
            if ((this.kt_lamdungtheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.kt_lamdungtheCompleted(this, new kt_lamdungtheCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws", ResponseNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal")]
        [return: System.Xml.Serialization.SoapElementAttribute("ws_dyncallReturn")]
        public string ws_dyncall(string _usr, string _pwd, string svcId, string param) {
            object[] results = this.Invoke("ws_dyncall", new object[] {
                        _usr,
                        _pwd,
                        svcId,
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ws_dyncallAsync(string _usr, string _pwd, string svcId, string param) {
            this.ws_dyncallAsync(_usr, _pwd, svcId, param, null);
        }
        
        /// <remarks/>
        public void ws_dyncallAsync(string _usr, string _pwd, string svcId, string param, object userState) {
            if ((this.ws_dyncallOperationCompleted == null)) {
                this.ws_dyncallOperationCompleted = new System.Threading.SendOrPostCallback(this.Onws_dyncallOperationCompleted);
            }
            this.InvokeAsync("ws_dyncall", new object[] {
                        _usr,
                        _pwd,
                        svcId,
                        param}, this.ws_dyncallOperationCompleted, userState);
        }
        
        private void Onws_dyncallOperationCompleted(object arg) {
            if ((this.ws_dyncallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ws_dyncallCompleted(this, new ws_dyncallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws", ResponseNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal")]
        [return: System.Xml.Serialization.SoapElementAttribute("guiTTNVReturn")]
        public string guiTTNV(string _usr, string _pwd, string xmlData) {
            object[] results = this.Invoke("guiTTNV", new object[] {
                        _usr,
                        _pwd,
                        xmlData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void guiTTNVAsync(string _usr, string _pwd, string xmlData) {
            this.guiTTNVAsync(_usr, _pwd, xmlData, null);
        }
        
        /// <remarks/>
        public void guiTTNVAsync(string _usr, string _pwd, string xmlData, object userState) {
            if ((this.guiTTNVOperationCompleted == null)) {
                this.guiTTNVOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguiTTNVOperationCompleted);
            }
            this.InvokeAsync("guiTTNV", new object[] {
                        _usr,
                        _pwd,
                        xmlData}, this.guiTTNVOperationCompleted, userState);
        }
        
        private void OnguiTTNVOperationCompleted(object arg) {
            if ((this.guiTTNVCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guiTTNVCompleted(this, new guiTTNVCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws", ResponseNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal")]
        [return: System.Xml.Serialization.SoapElementAttribute("guiTTXVReturn")]
        public string guiTTXV(string _usr, string _pwd, string xmlData) {
            object[] results = this.Invoke("guiTTXV", new object[] {
                        _usr,
                        _pwd,
                        xmlData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void guiTTXVAsync(string _usr, string _pwd, string xmlData) {
            this.guiTTXVAsync(_usr, _pwd, xmlData, null);
        }
        
        /// <remarks/>
        public void guiTTXVAsync(string _usr, string _pwd, string xmlData, object userState) {
            if ((this.guiTTXVOperationCompleted == null)) {
                this.guiTTXVOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguiTTXVOperationCompleted);
            }
            this.InvokeAsync("guiTTXV", new object[] {
                        _usr,
                        _pwd,
                        xmlData}, this.guiTTXVOperationCompleted, userState);
        }
        
        private void OnguiTTXVOperationCompleted(object arg) {
            if ((this.guiTTXVCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guiTTXVCompleted(this, new guiTTXVCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws", ResponseNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal")]
        [return: System.Xml.Serialization.SoapElementAttribute("guiTTCTReturn")]
        public string guiTTCT(string _usr, string _pwd, string xmlData) {
            object[] results = this.Invoke("guiTTCT", new object[] {
                        _usr,
                        _pwd,
                        xmlData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void guiTTCTAsync(string _usr, string _pwd, string xmlData) {
            this.guiTTCTAsync(_usr, _pwd, xmlData, null);
        }
        
        /// <remarks/>
        public void guiTTCTAsync(string _usr, string _pwd, string xmlData, object userState) {
            if ((this.guiTTCTOperationCompleted == null)) {
                this.guiTTCTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguiTTCTOperationCompleted);
            }
            this.InvokeAsync("guiTTCT", new object[] {
                        _usr,
                        _pwd,
                        xmlData}, this.guiTTCTOperationCompleted, userState);
        }
        
        private void OnguiTTCTOperationCompleted(object arg) {
            if ((this.guiTTCTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guiTTCTCompleted(this, new guiTTCTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws", ResponseNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal")]
        [return: System.Xml.Serialization.SoapElementAttribute("kt_tt_theBHYTReturn")]
        public string kt_tt_theBHYT(string _usr, string _pwd, string xmlData) {
            object[] results = this.Invoke("kt_tt_theBHYT", new object[] {
                        _usr,
                        _pwd,
                        xmlData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void kt_tt_theBHYTAsync(string _usr, string _pwd, string xmlData) {
            this.kt_tt_theBHYTAsync(_usr, _pwd, xmlData, null);
        }
        
        /// <remarks/>
        public void kt_tt_theBHYTAsync(string _usr, string _pwd, string xmlData, object userState) {
            if ((this.kt_tt_theBHYTOperationCompleted == null)) {
                this.kt_tt_theBHYTOperationCompleted = new System.Threading.SendOrPostCallback(this.Onkt_tt_theBHYTOperationCompleted);
            }
            this.InvokeAsync("kt_tt_theBHYT", new object[] {
                        _usr,
                        _pwd,
                        xmlData}, this.kt_tt_theBHYTOperationCompleted, userState);
        }
        
        private void Onkt_tt_theBHYTOperationCompleted(object arg) {
            if ((this.kt_tt_theBHYTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.kt_tt_theBHYTCompleted(this, new kt_tt_theBHYTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws", ResponseNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal")]
        [return: System.Xml.Serialization.SoapElementAttribute("tc_tt_theBHYTReturn")]
        public string tc_tt_theBHYT(string _usr, string _pwd, string xmlData) {
            object[] results = this.Invoke("tc_tt_theBHYT", new object[] {
                        _usr,
                        _pwd,
                        xmlData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void tc_tt_theBHYTAsync(string _usr, string _pwd, string xmlData) {
            this.tc_tt_theBHYTAsync(_usr, _pwd, xmlData, null);
        }
        
        /// <remarks/>
        public void tc_tt_theBHYTAsync(string _usr, string _pwd, string xmlData, object userState) {
            if ((this.tc_tt_theBHYTOperationCompleted == null)) {
                this.tc_tt_theBHYTOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontc_tt_theBHYTOperationCompleted);
            }
            this.InvokeAsync("tc_tt_theBHYT", new object[] {
                        _usr,
                        _pwd,
                        xmlData}, this.tc_tt_theBHYTOperationCompleted, userState);
        }
        
        private void Ontc_tt_theBHYTOperationCompleted(object arg) {
            if ((this.tc_tt_theBHYTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tc_tt_theBHYTCompleted(this, new tc_tt_theBHYTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws", ResponseNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal")]
        [return: System.Xml.Serialization.SoapElementAttribute("nhanTTCTReturn")]
        public string nhanTTCT(string _usr, string _pwd, string xmlData) {
            object[] results = this.Invoke("nhanTTCT", new object[] {
                        _usr,
                        _pwd,
                        xmlData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nhanTTCTAsync(string _usr, string _pwd, string xmlData) {
            this.nhanTTCTAsync(_usr, _pwd, xmlData, null);
        }
        
        /// <remarks/>
        public void nhanTTCTAsync(string _usr, string _pwd, string xmlData, object userState) {
            if ((this.nhanTTCTOperationCompleted == null)) {
                this.nhanTTCTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnhanTTCTOperationCompleted);
            }
            this.InvokeAsync("nhanTTCT", new object[] {
                        _usr,
                        _pwd,
                        xmlData}, this.nhanTTCTOperationCompleted, userState);
        }
        
        private void OnnhanTTCTOperationCompleted(object arg) {
            if ((this.nhanTTCTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nhanTTCTCompleted(this, new nhanTTCTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws", ResponseNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal")]
        [return: System.Xml.Serialization.SoapElementAttribute("tc_ls_KCBReturn")]
        public string tc_ls_KCB(string _usr, string _pwd, string xmlData) {
            object[] results = this.Invoke("tc_ls_KCB", new object[] {
                        _usr,
                        _pwd,
                        xmlData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void tc_ls_KCBAsync(string _usr, string _pwd, string xmlData) {
            this.tc_ls_KCBAsync(_usr, _pwd, xmlData, null);
        }
        
        /// <remarks/>
        public void tc_ls_KCBAsync(string _usr, string _pwd, string xmlData, object userState) {
            if ((this.tc_ls_KCBOperationCompleted == null)) {
                this.tc_ls_KCBOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontc_ls_KCBOperationCompleted);
            }
            this.InvokeAsync("tc_ls_KCB", new object[] {
                        _usr,
                        _pwd,
                        xmlData}, this.tc_ls_KCBOperationCompleted, userState);
        }
        
        private void Ontc_ls_KCBOperationCompleted(object arg) {
            if ((this.tc_ls_KCBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tc_ls_KCBCompleted(this, new tc_ls_KCBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws", ResponseNamespace="https://congdulieuyte.vn/hPortal/services/WSPortal")]
        [return: System.Xml.Serialization.SoapElementAttribute("guiDTTReturn")]
        public string guiDTT(string _usr, string _pwd, string xmlData) {
            object[] results = this.Invoke("guiDTT", new object[] {
                        _usr,
                        _pwd,
                        xmlData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void guiDTTAsync(string _usr, string _pwd, string xmlData) {
            this.guiDTTAsync(_usr, _pwd, xmlData, null);
        }
        
        /// <remarks/>
        public void guiDTTAsync(string _usr, string _pwd, string xmlData, object userState) {
            if ((this.guiDTTOperationCompleted == null)) {
                this.guiDTTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguiDTTOperationCompleted);
            }
            this.InvokeAsync("guiDTT", new object[] {
                        _usr,
                        _pwd,
                        xmlData}, this.guiDTTOperationCompleted, userState);
        }
        
        private void OnguiDTTOperationCompleted(object arg) {
            if ((this.guiDTTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guiDTTCompleted(this, new guiDTTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void nhanDTTCompletedEventHandler(object sender, nhanDTTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nhanDTTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nhanDTTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void guiDDTTCompletedEventHandler(object sender, guiDDTTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guiDDTTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guiDDTTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void nhanDDTTCompletedEventHandler(object sender, nhanDDTTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nhanDDTTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nhanDDTTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void kt_lamdungtheCompletedEventHandler(object sender, kt_lamdungtheCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class kt_lamdungtheCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal kt_lamdungtheCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ws_dyncallCompletedEventHandler(object sender, ws_dyncallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ws_dyncallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ws_dyncallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void guiTTNVCompletedEventHandler(object sender, guiTTNVCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guiTTNVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guiTTNVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void guiTTXVCompletedEventHandler(object sender, guiTTXVCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guiTTXVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guiTTXVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void guiTTCTCompletedEventHandler(object sender, guiTTCTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guiTTCTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guiTTCTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void kt_tt_theBHYTCompletedEventHandler(object sender, kt_tt_theBHYTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class kt_tt_theBHYTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal kt_tt_theBHYTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void tc_tt_theBHYTCompletedEventHandler(object sender, tc_tt_theBHYTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tc_tt_theBHYTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tc_tt_theBHYTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void nhanTTCTCompletedEventHandler(object sender, nhanTTCTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nhanTTCTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nhanTTCTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void tc_ls_KCBCompletedEventHandler(object sender, tc_ls_KCBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tc_ls_KCBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tc_ls_KCBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void guiDTTCompletedEventHandler(object sender, guiDTTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guiDTTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guiDTTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591